#!/bin/bash
# Switch screen to red vision to avoid destroying dark adaption of eyes
# when star gazing

# License: GPL 3.0
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Initialize flags
isZenity=0
isKdialog=0

if [ -e ~/.redscreen ] # check if redscreen is active by testing for flag file => set screen to normal
then	
	which zenity  >/dev/null 2>&1 # Test for Zenity
	if [ $? -eq 0 ]
	then 
		isZenity=1
	fi
	which kdialog >/dev/null 2>&1 # Test for Kdialog
	if [ $? -eq 0 ]
	then
		isKdialog=1
	fi
	# Process
	if [ $isZenity = 1 ] # If Zenity is installed
	then
		zenity --question --text="Set screen back to normal?" >/dev/null 2>&1
		if [ $? -eq 0 ]
		then
			xcalib -clear && rm ~/.redscreen
		fi
	elif [ $isKdialog = 1 ] # If Kdialog is installed
	then
		kdialog --yesno "Set screen back to normal?"
		if [ $? -eq 0 ]
		then
			xcalib -clear && rm ~/.redscreen
		fi
	else # if neither Zenity nor Kdialog is installed
		xcalib -clear && rm ~/.redscreen
	fi
else # Redscreen not active => set screen to red
	xcalib -green .1 0 1 -alter 
	xcalib -blue .1 0 1 -alter
	touch ~/.redscreen # set redscreen flag file
fi

